name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'hi, read this [readme](https://github.com/Abhijay007/Real-Time/blob/master/README.md)'
        pr-message: 'hi, read this [readme](https://github.com/Abhijay007/Real-Time/blob/master/README.md)'
